### ISSUE TITLE
Use bun as a bundler instead of parcel.

### ISSUE THREAD

**Issue by ezynda3** [gowebly/gowebly#103]
**Required check list:**

- [x] I didn't find in the repository's issues section a similar bug.
- [x] I understand, this is an Open Source and not-for-profit product.
- [x] This is not about a third-party project, framework, or technology.

**Is your feature request related to a problem? Please describe.**

Bun has great bundling features built-in. I would like the option to setup my project to use bun as the bundler rather than pull in parcel as another dependency.

...

**Describe the solution you'd like:**

Give a choice on which bundler to use with bun or when choosing bun as the frontend runner just use bun instead of parcel
...

**Describe alternatives you've considered:**

...

**Screenshots:**

...

**Additional context:**

...

**Comment by koddr** [comment]
Hi, @ezynda3 

Thank you for this issue 😉 

I also use Bun wherever possible, but there are many problems with it when you just need to mess with both JS and CSS so that it is simple and understandable. 

That's why I turned on Parcel, so that everyone could figure it out faster and start making cool applications, rather than fighting with the bundler config. 

But, if you have time, I'm ready to accept your vision of switching to Bun from Parcel in the form of PR.

**Comment by PylotLight** [comment]
I removed parcel and just use bun, seems to work for me btw.
