### ISSUE TITLE
port 5000 is taken by OS on a Mac these days.

### ISSUE THREAD

**Issue by gedw99** [gowebly/gowebly#28]
https://developer.apple.com/forums/thread/682332 

Basically on a Mac port 5000 is used by the OS.

**Comment by koddr** [comment]
Hi, @gedw99 

Yes, since the macOS Monterey, many developers have had their configs for Flask and many other Python and Go web frameworks broken.

There are two quick fixes here:

1. Disable the **AirPlay Receiver** feature in macOS settings, as this [comment](https://developer.apple.com/forums/thread/682332?answerId=678289022#678289022) says;
2. Before creating a project using the Gowebly CLI, change the `port` option in the config (in the `backend` block) from `5000` to any other option that will not be picked up by OS.

Also, I will change this default setting in future releases to remove _extra_ actions for the user. For example, to `7000`.

**Comment by gedw99** [comment]
yeah I change the port in the config, but yeah good idea to change the default

**Comment by koddr** [comment]
Fixed in `v1.7.0`
